# Generated by Django 2.2 on 2019-04-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cdr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calldate', models.DateTimeField()),
                ('clid', models.CharField(max_length=80)),
                ('src', models.CharField(max_length=80)),
                ('dst', models.CharField(max_length=80)),
                ('dcontext', models.CharField(max_length=80)),
                ('channel', models.CharField(max_length=80)),
                ('dstchannel', models.CharField(max_length=80)),
                ('lastapp', models.CharField(max_length=80)),
                ('lastdata', models.CharField(max_length=80)),
                ('duration', models.IntegerField()),
                ('billsec', models.IntegerField()),
                ('disposition', models.CharField(max_length=45)),
                ('amaflags', models.IntegerField()),
                ('accountcode', models.CharField(max_length=20)),
                ('uniqueid', models.CharField(max_length=32)),
                ('userfield', models.CharField(max_length=255)),
                ('did', models.CharField(max_length=50)),
                ('recordingfile', models.CharField(max_length=255)),
                ('cnum', models.CharField(max_length=80)),
                ('cnam', models.CharField(max_length=80)),
                ('outbound_cnum', models.CharField(max_length=80)),
                ('outbound_cnam', models.CharField(max_length=80)),
                ('dst_cnam', models.CharField(max_length=80)),
                ('linkedid', models.CharField(max_length=32)),
                ('peeraccount', models.CharField(max_length=80)),
                ('sequence', models.IntegerField()),
            ],
            options={
                'db_table': 'cdr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_rate', models.DateField()),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
            ],
        ),
    ]
