# Generated by Django 2.2 on 2019-04-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cdr',
            fields=[
                ('calldate', models.DateTimeField()),
                ('clid', models.CharField(max_length=240)),
                ('src', models.CharField(max_length=240)),
                ('dst', models.CharField(max_length=240)),
                ('dcontext', models.CharField(max_length=240)),
                ('channel', models.CharField(max_length=240)),
                ('dstchannel', models.CharField(max_length=240)),
                ('lastapp', models.CharField(max_length=240)),
                ('lastdata', models.CharField(max_length=240)),
                ('duration', models.IntegerField()),
                ('billsec', models.IntegerField()),
                ('disposition', models.CharField(max_length=135)),
                ('amaflags', models.IntegerField()),
                ('accountcode', models.CharField(max_length=60)),
                ('uniqueid', models.CharField(max_length=96, primary_key=True, serialize=False)),
                ('userfield', models.CharField(max_length=765)),
            ],
            options={
                'verbose_name': 'registro de llamada',
                'verbose_name_plural': 'registros de llamadas',
                'db_table': 'cdr',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_rate', models.DateField()),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
            ],
        ),
    ]
